spring:
  rabbitmq:
    virtual-host: /
    host: 192.168.1.9
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3

